import { useEffect, useState } from 'react'
import { Eye, EyeOff, Plus, Trash2 } from 'lucide-react'
import { api, idempotencyKey } from '../lib/api'
import { blindTokensForItem, encryptJson } from '../lib/crypto'
import { useVault } from '../lib/vault-context'
import { usePreferences } from '../lib/preferences'
import type { DecryptedItem, FieldDefinition, ItemMeta, ItemSecret, ItemType } from '../types'
import { Button } from './ui/Button'
import { Field, Input, Textarea } from './ui/Field'
import { SecureTextEditor } from './SecureTextEditor'
import { Modal } from './ui/Modal'
import { SecureNoteEditor } from './SecureNoteEditor'
import { useToast } from '../lib/toast'

const templates:Record<ItemType,{label:string;fields:Array<[string,string,'text'|'password'|'url'|'multiline']>}>= {
  login:{label:'Login',fields:[['password','Senha','password']]}, api_key:{label:'API Key',fields:[['api_key','API Key','password']]}, token:{label:'Token',fields:[['token','Token','password']]},
  database:{label:'Banco de dados',fields:[['host','Host','text'],['port','Porta','text'],['database','Database','text'],['password','Senha','password']]},
  ssh:{label:'SSH',fields:[['host','Host','text'],['port','Porta','text'],['private_key','Private key','multiline'],['passphrase','Passphrase','password']]},
  oauth:{label:'OAuth',fields:[['client_id','Client ID','text'],['client_secret','Client secret','password']]}, webhook:{label:'Webhook',fields:[['secret','Secret','password']]},
  secure_note:{label:'Nota segura',fields:[['note','Nota','multiline']]}, custom:{label:'Personalizado',fields:[]}
}
function defaultFields(type:ItemType):FieldDefinition[]{return templates[type].fields.map(([id,label,kind])=>({id,label,kind,protected:kind==='password'||kind==='multiline'}))}
function normalizeEnv(value:string){const v=value.toLowerCase();if(v.includes('homolog')||v.includes('stag'))return'staging';return'production'}

export function ItemForm({clientId,current,onClose,onSaved}:{clientId:string;current?:DecryptedItem;onClose:()=>void;onSaved:()=>void}){
 const {metadataKey,searchKey,secretEncryptKey}=useVault();const{t}=usePreferences();const{show}=useToast()
 const [visibleValues,setVisibleValues]=useState<Record<string,boolean>>({}); const [name,setName]=useState(current?.meta.name??''); const [type,setType]=useState<ItemType>(current?.meta.type??'login'); const [environment,setEnvironment]=useState(current?normalizeEnv(current.meta.environment):'production'); const [description,setDescription]=useState(current?.meta.description??''); const [url,setUrl]=useState(current?.meta.url??''); const [username,setUsername]=useState(current?.meta.username??''); const [tags,setTags]=useState(current?.meta.tags.join(', ')??''); const [scopes,setScopes]=useState(current?.meta.scopes.join(', ')??''); const [fields,setFields]=useState<FieldDefinition[]>(current?.meta.fields??defaultFields(type)); const [values,setValues]=useState<Record<string,string>>({}); const [replaceSecrets,setReplaceSecrets]=useState(!current); const [loading,setLoading]=useState(false); const [error,setError]=useState('')
 useEffect(()=>{if(!current){setFields(defaultFields(type));setValues({})}},[type,current])
 const addField=()=>{const id=crypto.randomUUID();setFields([...fields,{id,label:'Novo campo',kind:'text',protected:true}])}
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!metadataKey||!searchKey||!secretEncryptKey){setError('A sessão criptográfica não está disponível. Entre novamente.');return}setLoading(true);setError('');try{
   const effectiveFields=type==='secure_note'?[{id:'note',label:'Nota',kind:'multiline',protected:true} as FieldDefinition]:fields
   const meta:ItemMeta={schema:1,name:name.trim(),type,environment,description:description.trim(),url:type==='secure_note'?'':url.trim(),username:type==='secure_note'?'':username.trim(),tags:tags.split(',').map(x=>x.trim()).filter(Boolean),scopes:type==='secure_note'?[]:scopes.split(',').map(x=>x.trim()).filter(Boolean),fields:effectiveFields}
   const metadata=await encryptJson(metadataKey,meta);const search_tokens=await blindTokensForItem(searchKey,meta)
   if(current){const secret=replaceSecrets?await encryptJson(secretEncryptKey,{schema:1,values} satisfies ItemSecret):current.secret;await api(`/items/${current.id}`,{method:'PUT',body:JSON.stringify({metadata,secret,search_tokens,favorite:current.favorite})})}
   else{const secret=await encryptJson(secretEncryptKey,{schema:1,values} satisfies ItemSecret);await api('/items',{method:'POST',headers:{'Idempotency-Key':idempotencyKey()},body:JSON.stringify({client_id:clientId,metadata,secret,search_tokens,favorite:false})})}
   onSaved();show({kind:'success',title:current?'Credencial atualizada':'Credencial criada'});onClose()
 }catch(err){setError(err instanceof Error?err.message:'Não foi possível salvar a credencial.')}finally{setLoading(false)}}
 return <Modal title={current?'Editar credencial':'Nova credencial'} description={current?'Altere os dados necessários.':'A sessão autenticada permite criar a credencial sem confirmar a senha novamente.'} onClose={onClose} width="lg"><form onSubmit={save} className="space-y-6">
   <div className="grid gap-4 sm:grid-cols-2"><Field label={t('name')}><Input autoFocus value={name} maxLength={128} onChange={e=>setName(e.target.value)} required/></Field><Field label={t('type')}><select className="ui-input" value={type} onChange={e=>setType(e.target.value as ItemType)}>{Object.entries(templates).map(([v,x])=><option key={v} value={v}>{x.label}</option>)}</select></Field><Field label={t('environment')}><select className="ui-input" value={environment} onChange={e=>setEnvironment(e.target.value)}><option value="production">{t('production')}</option><option value="staging">{t('homologation')}</option></select></Field>{type!=='secure_note'&&<Field label="URL"><Input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://"/></Field>}{type!=='secure_note'&&<Field label={t('username')}><Input value={username} onChange={e=>setUsername(e.target.value)}/></Field>}<Field label={t('tags')}><Input value={tags} maxLength={64} onChange={e=>setTags(e.target.value)} placeholder="api, financeiro"/></Field></div>
   <Field label={t('description')} hint="Máximo de 256 caracteres."><SecureTextEditor value={description} onChange={setDescription} maxLength={256} placeholder="Contexto curto sobre esta credencial" minRows={5} fullscreenLabel="Abrir descrição em tela cheia"/></Field>
   {type!=='secure_note'&&<Field label={t('scopes')}><Input value={scopes} onChange={e=>setScopes(e.target.value)} placeholder="payments.read, payments.write"/></Field>}
   {current&&<div className="flex items-start justify-between gap-4 border-y border-ink/10 py-4"><div><p className="text-sm font-medium">Valores protegidos</p><p className="mt-1 text-sm text-ink/50">Os valores atuais ficam preservados até você optar por substituí-los.</p></div><label className="flex shrink-0 items-center gap-2 text-sm"><input type="checkbox" checked={replaceSecrets} onChange={e=>setReplaceSecrets(e.target.checked)}/> Substituir</label></div>}
   {replaceSecrets&&type==='secure_note'&&<Field label={t('note')} hint="Criptografada no navegador. Máximo de 1024 caracteres."><SecureNoteEditor value={values.note??''} onChange={value=>setValues({...values,note:value})}/></Field>}
   {replaceSecrets&&type!=='secure_note'&&<section><div className="mb-3 flex items-center justify-between"><div><h3 className="text-sm font-semibold">Campos protegidos</h3><p className="mt-1 text-sm text-ink/50">Os valores são criptografados antes de sair do navegador.</p></div><Button type="button" variant="secondary" icon={<Plus size={15}/>} onClick={addField}>Campo</Button></div><div className="overflow-hidden border border-ink/10 bg-surface rounded-ui">{fields.map((field,index)=><div key={field.id} className="grid gap-2 border-b border-ink/10 p-3 last:border-b-0 sm:grid-cols-[150px_115px_1fr_40px]"><Input value={field.label} onChange={e=>setFields(fields.map((f,i)=>i===index?{...f,label:e.target.value}:f))}/><select className="ui-input" value={field.kind} onChange={e=>setFields(fields.map((f,i)=>i===index?{...f,kind:e.target.value as FieldDefinition['kind']}:f))}><option value="text">Texto</option><option value="password">Senha</option><option value="url">URL</option><option value="multiline">Texto longo</option></select>{field.kind==='multiline'?<Textarea maxLength={1024} className="!min-h-10" value={values[field.id]??''} onChange={e=>setValues({...values,[field.id]:e.target.value})}/>:field.kind==='password'?<div className="relative"><Input type={visibleValues[field.id]?'text':'password'} className="pr-11" value={values[field.id]??''} onChange={e=>setValues({...values,[field.id]:e.target.value})}/><button type="button" className="absolute right-0 top-0 flex h-10 w-10 items-center justify-center text-ink/45 transition hover:text-ink" onClick={()=>setVisibleValues(v=>({...v,[field.id]:!v[field.id]}))} title={visibleValues[field.id]?'Ocultar valor':'Mostrar valor'}>{visibleValues[field.id]?<EyeOff size={16}/>:<Eye size={16}/>}</button></div>:<Input type="text" value={values[field.id]??''} onChange={e=>setValues({...values,[field.id]:e.target.value})}/>}<button type="button" className="ui-icon-button" onClick={()=>{setFields(fields.filter((_,i)=>i!==index));const n={...values};delete n[field.id];setValues(n)}}><Trash2 size={16}/></button></div>)}</div></section>}
   {error&&<p className="ui-error">{error}</p>}<div className="flex justify-end gap-2 border-t border-ink/10 pt-4"><Button type="button" variant="text" onClick={onClose}>{t('cancel')}</Button><Button variant="primary" disabled={loading||!name.trim()}>{loading?'Salvando...':t('saveCredential')}</Button></div>
 </form></Modal>
}
