import { useEffect, useMemo, useState } from 'react'
import { Search } from 'lucide-react'
import { api } from '../lib/api'
import { Timeline, TimelineItem } from '../components/ui/Timeline'
import { Skeleton } from '../components/ui/Skeleton'
import { Input } from '../components/ui/Field'
import { Button } from '../components/ui/Button'
import { usePreferences } from '../lib/preferences'

type Event={id:string;event:string;object_type:string|null;object_id:string|null;created_at:string}
type PageResponse={items:Event[];next_cursor:string|null}
export const auditLabels:Record<string,{pt:string;en:string;es:string}>={
 LOGIN:{pt:'Login realizado',en:'Signed in',es:'Inicio de sesión'},LOGOUT:{pt:'Sessão encerrada',en:'Signed out',es:'Sesión cerrada'},LOGIN_FAILED:{pt:'Falha de login',en:'Failed sign in',es:'Error de inicio de sesión'},
 CLIENT_CREATED:{pt:'Perfil criado',en:'Profile created',es:'Perfil creado'},CLIENT_UPDATED:{pt:'Perfil editado',en:'Profile updated',es:'Perfil editado'},CLIENT_TRASHED:{pt:'Perfil movido para a lixeira',en:'Profile moved to trash',es:'Perfil movido a la papelera'},CLIENT_RESTORED:{pt:'Perfil restaurado',en:'Profile restored',es:'Perfil restaurado'},CLIENT_DELETED:{pt:'Perfil excluído definitivamente',en:'Profile permanently deleted',es:'Perfil eliminado definitivamente'},
 ITEM_CREATED:{pt:'Credencial criada',en:'Credential created',es:'Credencial creada'},ITEM_UPDATED:{pt:'Credencial editada',en:'Credential updated',es:'Credencial editada'},ITEM_TRASHED:{pt:'Credencial movida para a lixeira',en:'Credential moved to trash',es:'Credencial movida a la papelera'},ITEM_RESTORED:{pt:'Credencial restaurada',en:'Credential restored',es:'Credencial restaurada'},
 SECRET_REVEALED:{pt:'Segredo revelado',en:'Secret revealed',es:'Secreto revelado'},SECRET_COPIED:{pt:'Segredo copiado',en:'Secret copied',es:'Secreto copiado'},OKY_EXPORTED:{pt:'Backup .oky exportado',en:'.oky backup exported',es:'Backup .oky exportado'},CSV_EXPORTED:{pt:'CSV exportado',en:'CSV exported',es:'CSV exportado'},LOCAL_BACKUP_CREATED:{pt:'Backup local criado',en:'Local backup created',es:'Backup local creado'},DRIVE_BACKUP_CREATED:{pt:'Backup enviado ao Drive',en:'Backup sent to Drive',es:'Backup enviado a Drive'},BACKUP_RESTORED:{pt:'Backup restaurado',en:'Backup restored',es:'Backup restaurado'},REAUTH:{pt:'Senha confirmada',en:'Password confirmed',es:'Contraseña confirmada'}
}
function label(event:string,locale:string){const row=auditLabels[event];return row?(locale==='en'?row.en:locale==='es'?row.es:row.pt):event}
export function AuditPage(){
 const{locale,t}=usePreferences();const[rows,setRows]=useState<Event[]>([]);const[loading,setLoading]=useState(true);const[nextCursor,setNextCursor]=useState<string|null>(null);const[q,setQ]=useState('');const[objectType,setObjectType]=useState('');const[eventGroup,setEventGroup]=useState('');const[limit,setLimit]=useState(50)
 const matchedEvents=useMemo(()=>{if(!eventGroup)return'';if(eventGroup==='profile')return Object.keys(auditLabels).filter(x=>x.startsWith('CLIENT_')).join(',');if(eventGroup==='credential')return Object.keys(auditLabels).filter(x=>x.startsWith('ITEM_')||x.startsWith('SECRET_')).join(',');if(eventGroup==='security')return ['LOGIN','LOGOUT','LOGIN_FAILED','REAUTH'].join(',');if(eventGroup==='backup')return Object.keys(auditLabels).filter(x=>x.includes('BACKUP')||x.includes('EXPORTED')).join(',');return''},[eventGroup])
 const load=async(reset=true)=>{setLoading(true);try{const p=new URLSearchParams({limit:String(limit)});if(!reset&&nextCursor)p.set('cursor',nextCursor);if(objectType)p.set('object_type',objectType);if(matchedEvents)p.set('events',matchedEvents);if(q.trim()&&/^[A-Z_]+$/i.test(q.trim()))p.set('q',q.trim());const page=await api<PageResponse>(`/audit?${p}`);let items=page.items;if(q.trim()&&!/^[A-Z_]+$/i.test(q.trim())){const term=q.toLocaleLowerCase(locale);items=items.filter(r=>label(r.event,locale).toLocaleLowerCase(locale).includes(term)||r.object_id?.toLowerCase().includes(term))}setRows(prev=>reset?items:[...prev,...items]);setNextCursor(page.next_cursor)}finally{setLoading(false)}}
 useEffect(()=>{const h=window.setTimeout(()=>load(true),180);return()=>window.clearTimeout(h)},[q,objectType,eventGroup,limit,locale])
 return <Page fill title={t('audit')} description="Histórico de ações relevantes. Valores secretos nunca aparecem aqui."><div className="ui-section flex min-h-0 flex-1 flex-col overflow-hidden"><div className="grid gap-2 border-b border-ink/10 bg-surface p-3 md:grid-cols-[1fr_180px_180px_140px]"><div className="relative"><Search size={15} className="absolute left-3 top-3 text-ink/35"/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder={t('auditSearch')} className="pl-9"/></div><select className="ui-input" value={eventGroup} onChange={e=>setEventGroup(e.target.value)}><option value="">{t('allEvents')}</option><option value="profile">{t('profile')}</option><option value="credential">{t('credential')}</option><option value="security">Segurança</option><option value="backup">Backup</option></select><select className="ui-input" value={objectType} onChange={e=>setObjectType(e.target.value)}><option value="">{t('allObjects')}</option><option value="client">{t('profile')}</option><option value="item">{t('credential')}</option><option value="session">Sessão</option><option value="vault">Cofre</option></select><select className="ui-input" value={limit} onChange={e=>setLimit(Number(e.target.value))}><option value={25}>25 / página</option><option value={50}>50 / página</option><option value={100}>100 / página</option></select></div><div className="ok-scrollbar min-h-0 flex-1 overflow-y-auto p-5 sm:p-6">{loading&&rows.length===0?<div className="space-y-4"><Skeleton className="h-12"/><Skeleton className="h-12"/><Skeleton className="h-12"/></div>:rows.length?<Timeline>{rows.map(r=><TimelineItem key={r.id} title={label(r.event,locale)} meta={new Date(r.created_at).toLocaleString(locale)}>{r.object_type&&<p className="mt-1 font-mono text-[11px] text-ink/35">{r.object_type==='client'?t('profile').toLowerCase():r.object_type==='item'?t('credential').toLowerCase():r.object_type} {r.object_id?.slice(0,8)??''}</p>}</TimelineItem>)}</Timeline>:<p className="py-14 text-center text-sm text-ink/45">Nenhum evento encontrado.</p>}{nextCursor&&<div className="mt-5 flex justify-center"><Button disabled={loading} onClick={()=>load(false)}>{t('loadMore')}</Button></div>}</div></div></Page>
}
export function Page({title,description,children,fill=false}:{title:string;description?:string;children:React.ReactNode;fill?:boolean}){return <main className={`mx-auto w-full max-w-6xl px-4 py-6 sm:px-7 sm:py-8 ${fill?'flex h-[calc(100vh-64px)] min-h-0 flex-col overflow-hidden':''}`}><header className="mb-6 shrink-0"><h1 className="text-xl font-semibold tracking-tight">{title}</h1>{description&&<p className="mt-1.5 max-w-2xl text-sm leading-6 text-ink/50">{description}</p>}</header>{children}</main>}
