import { useEffect, useMemo, useState } from 'react'
import { Clock3, MoreHorizontal, Pencil, Plus, Search, Trash2 } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { api } from '../lib/api'
import { blindTokensForQuery, decryptJson } from '../lib/crypto'
import { useVault } from '../lib/vault-context'
import { usePreferences } from '../lib/preferences'
import type { ClientMeta, ClientRow, DecryptedClient, DecryptedItem, ItemMeta, ItemRow } from '../types'
import { ClientForm } from '../components/ClientForm'
import { ItemForm } from '../components/ItemForm'
import { ItemDetail } from '../components/ItemDetail'
import { DeleteClientDialog } from '../components/DeleteClientDialog'
import { ClientTimeline } from '../components/ClientTimeline'
import { Button } from '../components/ui/Button'
import { EmptyState } from '../components/ui/EmptyState'
import { Input } from '../components/ui/Field'
import { Skeleton } from '../components/ui/Skeleton'
import { usePrivacy } from '../lib/privacy'

async function decryptClient(row:ClientRow,key:Uint8Array){return {...row,meta:await decryptJson<ClientMeta>(key,row.metadata)}}
async function decryptItems(rows:ItemRow[],key:Uint8Array){return Promise.all(rows.map(async r=>({...r,meta:await decryptJson<ItemMeta>(key,r.metadata})))}
function envLabel(v:string,t:(k:string)=>string){return v==='staging'||v==='homologation'||v.toLowerCase().includes('homolog')?t('homologation'):t('production')}

export function VaultPage(){
 const {metadataKey,searchKey}=useVault();const{t}=usePreferences();const{hideCredentialNames}=usePrivacy();const[params,setParams]=useSearchParams();const clientId=params.get('client')??undefined;const globalQuery=params.get('q')??''
 const [client,setClient]=useState<DecryptedClient>();const[items,setItems]=useState<DecryptedItem[]>([]);const[selectedItem,setSelectedItem]=useState<DecryptedItem>();const[itemQuery,setItemQuery]=useState('');const[tab,setTab]=useState<'credentials'|'activity'>('credentials');const[newItem,setNewItem]=useState(false);const[editItem,setEditItem]=useState(false);const[editClient,setEditClient]=useState(false);const[deleteClient,setDeleteClient]=useState(false);const[loading,setLoading]=useState(true);const[nextCursor,setNextCursor]=useState<string|null>(null)
 const loadClient=async(id:string)=>{if(!metadataKey)return;const row=await api<ClientRow>(`/clients/${id}`);setClient(await decryptClient(row,metadataKey))}
 const loadItems=async(reset=true)=>{if(!metadataKey||!clientId){setItems([]);return}const q=new URLSearchParams({client_id:clientId,limit:'50'});if(!reset&&nextCursor)q.set('cursor',nextCursor);const page=await api<{items:ItemRow[];next_cursor:string|null}>(`/items?${q}`);const dec=await decryptItems(page.items,metadataKey);setItems(prev=>reset?dec:[...prev,...dec]);setNextCursor(page.next_cursor);if(reset)setSelectedItem(undefined)}
 const chooseFirstClient=async()=>{if(!metadataKey)return;const page=await api<{items:ClientRow[]}>('/clients?limit=1');if(page.items[0]){setParams(p=>{p.set('client',page.items[0].id);return p},{replace:true})}else{setClient(undefined);setItems([])}}
 const globalSearch=async(q:string)=>{if(!metadataKey||!searchKey)return;const tokens=await blindTokensForQuery(searchKey,q);if(!tokens.length)return;const res=await api<{clients:ClientRow[];items:ItemRow[]}>('/search',{method:'POST',body:JSON.stringify({tokens,scope:'all',limit:100})});const decItems=await decryptItems(res.items,metadataKey);setItems(decItems);setNextCursor(null);setSelectedItem(undefined);if(res.clients[0])setClient(await decryptClient(res.clients[0],metadataKey));else if(decItems[0]){try{await loadClient(decItems[0].client_id)}catch{setClient(undefined)}}}
 useEffect(()=>{if(!metadataKey)return;setLoading(true);(async()=>{if(globalQuery.trim()){await globalSearch(globalQuery)}else if(clientId){await loadClient(clientId);await loadItems(true)}else await chooseFirstClient()})().finally(()=>setLoading(false))},[metadataKey,clientId,globalQuery])
 useEffect(()=>{const h=()=>{if(clientId){loadClient(clientId);loadItems(true)}};window.addEventListener('ocultakey:items-changed',h);return()=>window.removeEventListener('ocultakey:items-changed',h)},[clientId,metadataKey])
 useEffect(()=>{if(globalQuery||!clientId)return;const h=window.setTimeout(async()=>{if(!searchKey||!metadataKey)return;if(!itemQuery.trim()){await loadItems(true);return}const tokens=await blindTokensForQuery(searchKey,itemQuery);if(!tokens.length)return;const res=await api<{items:ItemRow[]}>('/search',{method:'POST',body:JSON.stringify({tokens,scope:'items',client_id:clientId,limit:100})});setItems(await decryptItems(res.items,metadataKey));setSelectedItem(undefined);setNextCursor(null)},180);return()=>window.clearTimeout(h)},[itemQuery,clientId,globalQuery])
 const shownItems=useMemo(()=>items,[items]);const saved=()=>{window.dispatchEvent(new Event('ocultakey:items-changed'));loadItems(true)}
 if(loading)return <div className="grid h-[calc(100vh-64px)] lg:grid-cols-[minmax(360px,42%)_1fr]"><div className="border-r border-ink/10 bg-surface p-6"><Skeleton className="h-8 w-48"/><Skeleton className="mt-3 h-4 w-72"/><div className="mt-8 space-y-3"><Skeleton className="h-16"/><Skeleton className="h-16"/><Skeleton className="h-16"/></div></div><div className="hidden p-7 lg:block"><Skeleton className="h-8 w-56"/><Skeleton className="mt-6 h-12"/></div></div>
 if(!client&&!globalQuery)return <EmptyState title={t('noProfiles')} description="Crie o primeiro perfil pela barra lateral para começar a organizar as credenciais."/>
 return <div className="grid h-[calc(100vh-64px)] min-h-0 lg:grid-cols-[minmax(380px,42%)_1fr]">
  <section className={`${selectedItem?'hidden lg:flex':'flex'} min-h-0 flex-col border-r border-ink/10 bg-surface`}>
   <div className="shrink-0 border-b border-ink/10 px-5 py-5 sm:px-6"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="text-xs font-medium text-ink/45">{globalQuery?'Resultados':t('profile')}</p><h1 className="mt-1 truncate text-xl font-semibold tracking-tight">{globalQuery?`“${globalQuery}”`:client?.meta.name??t('profiles')}</h1>{!globalQuery&&client?.meta.description&&<p className="mt-2 line-clamp-2 text-sm leading-5 text-ink/50">{client.meta.description}</p>}</div>{client&&!globalQuery&&<div className="flex shrink-0 gap-1"><button className="ui-icon-button" onClick={()=>setEditClient(true)} title="Editar perfil"><Pencil size={17}/></button><button className="ui-icon-button" onClick={()=>setDeleteClient(true)} title="Excluir perfil"><Trash2 size={17}/></button></div>}</div>
   {!globalQuery&&client&&<div className="mt-5 flex border-b border-ink/10"><button className={`ui-tab ${tab==='credentials'?'ui-tab-active':''}`} onClick={()=>setTab('credentials')}>{t('credentials')}</button><button className={`ui-tab ${tab==='activity'?'ui-tab-active':''}`} onClick={()=>setTab('activity')}><Clock3 size={14}/> {t('activity')}</button></div>}</div>
   {tab==='activity'&&!globalQuery&&client?<div className="min-h-0 flex-1 overflow-hidden p-5 sm:p-6"><ClientTimeline clientId={client.id}/></div>:<><div className="shrink-0 flex items-center gap-2 border-b border-ink/10 px-5 py-3 sm:px-6"><div className="relative min-w-0 flex-1"><Search size={15} className="absolute left-3 top-3 text-ink/35"/><Input value={itemQuery} onChange={e=>setItemQuery(e.target.value)} placeholder="Buscar credencial" className="pl-9"/></div><Button variant="primary" icon={<Plus size={16}/>} disabled={!clientId} onClick={()=>setNewItem(true)}>{t('newCredential')}</Button></div>
   <div className="ok-scrollbar min-h-0 flex-1 overflow-y-auto">{shownItems.map(item=><button key={item.id} onClick={()=>setSelectedItem(item)} className={`ui-list-row min-h-[68px] justify-between ${selectedItem?.id===item.id?'bg-action/[.07]':''}`}><div className="min-w-0"><div className="flex items-center gap-2"><span className="truncate text-sm font-medium">{hideCredentialNames?'••••••••':item.meta.name}</span></div><div className="mt-1 flex items-center gap-2 text-xs text-ink/45"><span>{item.meta.type.replace('_',' ')}</span><span>•</span><span>{envLabel(item.meta.environment,t)}</span></div></div><span className="shrink-0 font-mono text-xs tracking-wider text-ink/25">••••••</span></button>)}{shownItems.length===0&&<EmptyState title={t('noCredentials')} description={itemQuery?'Nenhum resultado para esta busca.':'Cadastre a primeira credencial deste perfil.'} action={!itemQuery&&clientId?<Button variant="primary" onClick={()=>setNewItem(true)}>{t('newCredential')}</Button>:undefined}/>} {nextCursor&&<div className="p-4"><Button className="w-full" onClick={()=>loadItems(false)}>{t('loadMore')}</Button></div>}</div></>}
  </section>
  <section className={`${selectedItem?'block':'hidden lg:block'} min-h-0 bg-canvas`}>{selectedItem?<ItemDetail item={selectedItem} onBack={()=>setSelectedItem(undefined)} onEdit={()=>setEditItem(true)} onDeleted={()=>{setSelectedItem(undefined);loadItems(true)}}/>:<div className="flex h-full min-h-0 items-center justify-center overflow-auto px-8 text-center"><div className="max-w-sm"><MoreHorizontal className="mx-auto text-ink/20"/><p className="mt-3 text-sm font-medium">{t('selectCredential')}</p><p className="mt-1 text-sm leading-6 text-ink/45">{t('selectCredentialHelp')}</p></div></div>}</section>
  {editClient&&client&&<ClientForm current={client} onClose={()=>setEditClient(false)} onSaved={()=>loadClient(client.id)}/>} {deleteClient&&client&&<DeleteClientDialog client={client} onClose={()=>setDeleteClient(false)} onDeleted={()=>{setParams({});setClient(undefined);setItems([])}}/>} {newItem&&clientId&&<ItemForm clientId={clientId} onClose={()=>setNewItem(false)} onSaved={saved}/>} {editItem&&selectedItem&&<ItemForm clientId={selectedItem.client_id} current={selectedItem} onClose={()=>setEditItem(false)} onSaved={saved}/>} 
 </div>
}
